# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUjr1jVgQ06MACvxsSF2xB3UtRgFqrm3
"""

import gradio as gr
from common import load_reviews

def refresh():
    return load_reviews()

gr.Interface(
    fn=refresh,
    inputs=[],
    outputs=gr.Dataframe(),
    title="Admin Dashboard - Live Reviews"
).launch(share=True)

def load_reviews():
    if os.path.exists("reviews.csv"):
        return pd.read_csv("reviews.csv")
    else:
        return pd.DataFrame(columns=["timestamp", "rating", "review", "ai_response"])

import importlib
import common
importlib.reload(common)
from common import load_reviews

