# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiD6eqdAHtKJx6Xo4MC55nyr8N-3wpUa
"""

import os
os.listdir()

import gradio as gr
from common import generate_user_response, save_review

def submit_review(rating, review):
    ai_response = generate_user_response(review, rating)
    save_review(rating, review, ai_response)
    return ai_response

gr.Interface(
    fn=submit_review,
    inputs=[
        gr.Slider(1, 5, step=1, label="Star Rating"),
        gr.Textbox(lines=4, label="Write your review")
    ],
    outputs=gr.Textbox(label="AI Response"),
    title="User Feedback Portal"
).launch(share=True)

