# -*- coding: utf-8 -*-
"""common.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BTML1-Qvq3k_vrhGlpgOqUHBAK_j0Abm
"""

import csv
import os
import pandas as pd
from datetime import datetime

DATA_PATH = "reviews.csv"

def generate_user_response(review, rating):
    if rating >= 4:
        return "Thank you for your positive feedback! We're glad you enjoyed our service."
    elif rating == 3:
        return "Thanks for your feedback. We'll work to improve your experience."
    else:
        return "We're sorry for your experience. We'll take your feedback seriously."

def save_review(rating, review, ai_response):
    file_exists = os.path.exists(DATA_PATH)

    with open(DATA_PATH, "a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        if not file_exists:
            writer.writerow(["timestamp", "rating", "review", "ai_response"])
        writer.writerow([datetime.now(), rating, review, ai_response])

def load_reviews():
    if os.path.exists(DATA_PATH):
        return pd.read_csv(DATA_PATH)
    else:
        return pd.DataFrame(columns=["timestamp", "rating", "review", "ai_response"])





